### ISSUE TITLE
Links to Distros no longer seem vaild

### ISSUE THREAD

**Issue by JohnShortland** [Layer8Err/WSL2setup#9]
First part of the script seems to work OK, however after reboot and rerun it can't obtain the appx files from the store:

`
Exception calling "write" with "1" argument(s): "Type mismatch.
"
At line:95 char:5
+     $newHtml.write($src)
+     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException

Invoke-WebRequest : Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At line:225 char:32
+         Invoke-WebRequest -Uri $distro.URI -OutFile $Filename -UseBas ...
+                                ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-WebRequest], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
`

**Comment by Layer8Err** [comment]
No longer using Invoke-WebRequest to download files.
